Installing rubygems conditionally
The new behavior is to only install rubygems if the version to install is
different to the one shipped with ruby.
If the version is the same, then don't re install it.

diff --git a/packages/ruby-3.1/packaging b/packages/ruby-3.1/packaging
--- a/packages/ruby-3.1/packaging
+++ b/packages/ruby-3.1/packaging
@@ -64,16 +64,19 @@ cp runtime-3.1.env "${BOSH_INSTALL_TARGET}/bosh/runtime.env"
 
 source "${BOSH_INSTALL_TARGET}/bosh/runtime.env"
 
-tar zxvf "rubygems-${RUBYGEMS_VERSION}.tgz"
-(
-  set -e
-  cd "rubygems-${RUBYGEMS_VERSION}"
+if [ "$(gem --version)" != "${RUBYGEMS_VERSION}" ]; then
+  echo "Installing rubygems " "${RUBYGEMS_VERSION}"
+  tar zxvf "rubygems-${RUBYGEMS_VERSION}.tgz"
+  (
+    set -e
+    cd "rubygems-${RUBYGEMS_VERSION}"
 
-  if ! ruby setup.rb --no-ri --no-rdoc; then
-    echo "Cannot install rubygems"
-    exit 1
-  fi
-)
+    if ! ruby setup.rb --no-ri --no-rdoc; then
+      echo "Cannot install rubygems"
+      exit 1
+    fi
+  )
+fi
 
 # We need to replace the shebang in the default binstubs generated by rubygems.
 # As of rubygems 2.7.6 and ruby 2.4.4 they fixed a vulnerability with regards
