compile ruby with openssl on darwin
[#151268855](https://www.pivotaltracker.com/story/show/151268855)

Signed-off-by: Neha Jain <jneha@vmware.com>

diff --git a/packages/ruby-2.4/packaging b/packages/ruby-2.4/packaging
--- a/packages/ruby-2.4/packaging
+++ b/packages/ruby-2.4/packaging
@@ -7,6 +7,14 @@ RUBYGEMS_VERSION=2.6.4
 BUNDLER_VERSION=1.15.3
 LIBYAML_VERSION=0.1.7
 
+openssl_version=`PATH=/usr/local/opt/openssl/bin:$PATH openssl version`
+openssl_major_version=`echo $openssl_version | cut -f2 -d\ | cut -f1 -d.`
+if [ $openssl_major_version == 0 ]; then
+  echo "OpenSSL version 1 or greater is required."
+  echo "Currently available: ${openssl_version}"
+  exit 1
+fi
+
 tar xzf "yaml-${LIBYAML_VERSION}.tar.gz"
 (
   set -e
@@ -30,7 +38,7 @@ tar xzf "ruby-${RUBY_VERSION}.tar.gz"
     cp ${BOSH_COMPILE_TARGET}/config/config.{guess,sub} ./tool
   fi
 
-  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET} --without-gmp
+  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=/usr/local/opt/openssl:${BOSH_INSTALL_TARGET} --without-gmp
   make
   make install
 )
